### PR TITLE
Update themes to the latest from mkdocs core

### PR DESCRIPTION
**Pull request by jimporter**
@waylan This adds the following changes from mkdocs core to the bootswatch themes. I just copied the files over to `src/_base` and then added the CSS changes from the keyboard nav commit. I did a quick local test and everything appears to be working.

* Add plugin API
* Add keyboard navigation
* Add "edit link" support

### CODE REVIEW

**Comment by waylan** [comment]
@jimporter thanks for keeping these up-to-date.

Btw, the 01.7 release of MkDocs includes support for themes to [extend][1] other themes. Rather than needing to "generate" the themes here, I wonder of inheritance should be used instead. In fact, I expect that these themes could all extend the `mkdocs` theme. That way, they would get any (non CSS) updates automatically. If, for some reason, they can't extend the `mkdocs` theme, they should be able to extend on of their own (set one as the base which is a complete theme and all other extend it only providing the files that differ). I accepted this PR anyway because it included CSS changes which still needed to be made, but using inheritance should cut down on the work to keep things up-to-date.

[1]: http://www.mkdocs.org/user-guide/custom-themes/#extends

**Comment by marcelstoer** [comment]
Shouldn't this have bumped the version in `setup.py`? Also, in strict mode the theme config file in `_base` doesn't seem to be picked up: https://github.com/mkdocs/mkdocs-bootswatch/issues/38#issuecomment-359127584

**Comment by waylan** [comment]
@marcelstoer the version will be bumped when a new version is released. I don't have the ability to upload a new release (to PyPI) and those who do seem to not be interested in doing so. Until then, we won't get any new versions of these themes.

**Comment by marcelstoer** [comment]
Thanks for  the feedback Waylan. Who are _they_? Can they be pinged and asked for help?

**Comment by dschwabeS11** [comment]
Can we somehow fix this problem with the themes? We have to stick to mkdocs 0.16.3 right now because of this problem. Is there a way to workarround this issue with the theme files to be able to use the latest mkdocs version?

**Comment by dschwabeS11** [comment]
Yes of course, but it would be better if it was fixed properly.

**Comment by waylan** [comment]
@Wdavery we have made multiple releases since the above comment was made. And, in fact, no changes have been made since the most recent release. Therefore you should be able to an official release rather than directly from git.

That said, the error is because the most recent release of the theme required MkDocs version 1.0 or later, but such a version was not found. I'm guess you have an early version of Python version 2.7 (prior to 2.7.9) as MkDocs 1.0 requires Python 2.7.9 or later. If you don't specify any versions in your pip command, then the latest available for your system will be installed. If you really want/need the latest version, then you will need to update Python as well.

**Comment by Wdavery** [comment]
Thanks for the quick help! You are exactly right about the python version so that all makes sense.

**Pull request merged**
